/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: '0314_F407VET6' 
 * Target:  '0314_F407VET6' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* GorgonMeducer::Utilities:perf_counter:Core&Source@2.4.0 */
#define __PERF_COUNTER__ 1


#endif /* RTE_COMPONENTS_H */
